import { buildCard } from "@/lib/scoring/engine";
import type { Card, Signals } from "@/lib/scoring/types";

const RAW: Signals[] = [
  {
    login: "@mrbeast",
    name: "MrBeast",
    avatarUrl: "https://unavatar.io/youtube/mrbeast",
    location: "US",
    subscribers: 300000000,
    channel_age_years: 12.5,
    video_count: 810,
    total_views: 52000000000,
    avg_views_recent: 155000000,
    category_count: 3,
    rankedCategories: ["24", "23", "22"],
    topCategory: "24",
    recent_uploads: 26,
    active_years: 12,
    avg_likes_recent: 8500000,
    avg_comments_recent: 240000,
    recent_spike: true,
  },
  {
    login: "@mkbhd",
    name: "Marques Brownlee",
    avatarUrl: "https://unavatar.io/youtube/mkbhd",
    location: "US",
    subscribers: 19100000,
    channel_age_years: 15.2,
    video_count: 1650,
    total_views: 4300000000,
    avg_views_recent: 3200000,
    category_count: 2,
    rankedCategories: ["28", "24"],
    topCategory: "28",
    recent_uploads: 95,
    active_years: 15,
    avg_likes_recent: 160000,
    avg_comments_recent: 12000,
    recent_spike: false,
  },
  {
    login: "@pewdiepie",
    name: "PewDiePie",
    avatarUrl: "https://unavatar.io/youtube/pewdiepie",
    location: "JP",
    subscribers: 111000000,
    channel_age_years: 14.1,
    video_count: 4750,
    total_views: 29200000000,
    avg_views_recent: 1400000,
    category_count: 4,
    rankedCategories: ["20", "23", "24", "22"],
    topCategory: "20",
    recent_uploads: 12,
    active_years: 14,
    avg_likes_recent: 950000,
    avg_comments_recent: 9000,
    recent_spike: false,
  },
  {
    login: "@theprimeagen",
    name: "ThePrimeagen",
    avatarUrl: "https://unavatar.io/youtube/theprimeagen",
    location: "US",
    subscribers: 460000,
    channel_age_years: 5.1,
    video_count: 1180,
    total_views: 65000000,
    avg_views_recent: 125000,
    category_count: 2,
    rankedCategories: ["28", "20"],
    topCategory: "28",
    recent_uploads: 160,
    active_years: 5,
    avg_likes_recent: 8500,
    avg_comments_recent: 780,
    recent_spike: false,
  },
];

export const SAMPLE_CARDS: Card[] = RAW.map(buildCard);
export const SAMPLE_LOGINS = RAW.map((r) => r.login);
